# Generated by Django 4.2.2 on 2023-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoryManagement', '0002_alter_category_cat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='categoryManagement.category')),
            ],
        ),
    ]
