# Generated by Django 4.2.2 on 2023-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='category_offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_offer/images/'),
        ),
    ]
