# Generated by Django 4.2.2 on 2023-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='category_offer_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
