# Generated by Django 4.2.2 on 2023-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0002_categoryoffer_category_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category_offer_image',
            field=models.ImageField(upload_to='category_offer/images/'),
        ),
    ]
