# Generated by Django 4.2.2 on 2023-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
        ('offer_management', '0003_alter_categoryoffer_category_offer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('discount_percentage', models.IntegerField(default=0)),
                ('product_offer_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_offer_image', models.ImageField(upload_to='product_offer/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(to='product_management.product_variant')),
            ],
        ),
    ]
