# Generated by Django 4.2.2 on 2023-07-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='banner/images/')),
                ('banner_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
