# Generated by Django 4.2.2 on 2023-07-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_url',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
