# Generated by Django 4.2.2 on 2023-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_recentviewedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentviewedproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
