# Generated by Django 4.2.2 on 2023-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
