# Generated by Django 4.2.2 on 2023-07-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_product_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=10)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
