# Generated by Django 4.2.2 on 2023-07-14 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 47, 44, 767523, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
