# Generated by Django 4.2.2 on 2023-07-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adressbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adressbook',
            name='email',
        ),
    ]
