# Generated by Django 4.2.2 on 2023-06-25 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.CharField(default='<function uuid4 at 0x0000021EC9BB0EE0>', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserOtp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
