# Generated by Django 4.2.2 on 2023-06-25 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='uid',
            field=models.CharField(default={uuid.uuid4}, max_length=200),
        ),
    ]
