# Generated by Django 4.2.2 on 2023-07-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletTransactions',
            new_name='WalletTransaction',
        ),
    ]
