# Generated by Django 4.2.2 on 2023-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
