# Generated by Django 4.2.2 on 2023-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_additional_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
